defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
  max_retries_on_connection_failure: 10

development:
  <<: *defaults
  database: mime_development

test:
  <<: *defaults
  logger: false
  database: mime_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
  # <<: *defaults
  # database: mime_production
